name: projeto_final

description: ZapZap Chat.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_messaging: ^14.7.5
  cloud_firestore: ^4.13.2
  image_picker: ^1.0.4
  firebase_storage: ^11.5.2
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.1.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 19

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/lottie/
